os: linux
dist: bionic
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - openmpi-bin
      - libnuma-dev
      - libopenmpi-dev
language: cpp

env:
  - TEST_SUITE="travis/build_debug_documentation.sh"
  - TEST_SUITE="travis/build_n1.sh"
  - TEST_SUITE="travis/build_n2.sh"
  - TEST_SUITE="travis/build_n3.sh"
  - TEST_SUITE="travis/build_n4.sh"

before_install:
  - cd tests
  - wget https://github.com/google/googletest/archive/release-1.10.0.zip
  - unzip release-1.10.0.zip
  - mv googletest-release-1.10.0 gtest-1.7.0    # FIXME PLEASE AS IN #40
  - cd ..

script:
  - sh ${TEST_SUITE}
