mkdir build_n2 && cd build_n2
cmake -DARGO_BACKEND_MPI=ON -DARGO_BACKEND_SINGLENODE=OFF -DARGO_TESTS=ON -DARGO_TESTS_NPROCS=2 -DARGO_DEBUG=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc ../
make -j2
make test
