mkdir build_debug && cd build_debug
cmake -DARGO_BACKEND_MPI=ON -DARGO_BACKEND_SINGLENODE=ON -DARGO_TESTS=ON -DARGO_TESTS_NPROCS=1 -DARGO_DEBUG=ON -DBUILD_DOCUMENTATION=ON -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc ../
make -j 2
make test
