mkdir build_n1 && cd build_n1
cmake -DARGO_BACKEND_MPI=ON -DARGO_BACKEND_SINGLENODE=ON -DARGO_TESTS=ON -DARGO_TESTS_NPROCS=1 -DARGO_DEBUG=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc ../
make -j 2
make test
