mkdir build_n4 && cd build_n4
cmake -DARGO_BACKEND_MPI=ON -DARGO_BACKEND_SINGLENODE=OFF -DARGO_TESTS=ON -DARGO_TESTS_NPROCS=4 -DARGO_DEBUG=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc ../
make -j2
make test
